### ISSUE TITLE
Plot 

### ISSUE THREAD

**Issue by INNFINITEMINDS** [darshanmandge/DRGsomamodel#1]
RESPECTED SIR,
CAN U PLEASE HELP HOW CAN I PLOT steady state parameter and time constant
like that of Hh.Also sir how did u plot this graphs in the paper .

I want to plot the graphs.(steady state parameter and time constant)
Hope u will help.also if u have some links than please share so that I will take it as reference.
Awaiting for your response.
Thank you,
Peace

**Comment by darshanmandge** [comment]
Your question is answered here: 
https://www.neuron.yale.edu/phpBB/viewtopic.php?f=28&t=1156
**Using the Grapher to plot voltage-dependent gating variables**

**Comment by INNFINITEMINDS** [comment]
THANK  YOU SIR , FOR YOUR RESPONSE .
I WILL TRY IT! THANKS ONCE AGAIN SIR.
peace:)
